[versions]
androidDesugarJdkLibs = "1.2.0"
kotlin = "1.7.21"
androidGradlePlugin = "7.3.1"
ktx = "1.9.0"
composeCompiler = "1.4.0-alpha02"
compose = "1.4.0-alpha02"
accompanist = "0.28.0"
material = "1.8.0-alpha02"
material3Compose = "1.1.0-alpha02"
lifecycle = "2.6.0-alpha03"
coroutines = "1.6.4"
ktor = "2.1.3"

[libraries]
android-desugarJdkLibs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "androidDesugarJdkLibs" }
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }

kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

android-material = { module = "com.google.android.material:material", version.ref = "material" }

androidx-appcompat = "androidx.appcompat:appcompat:1.7.0-alpha01"
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "ktx" }

androidx-compose-ui-core = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3Compose" }
androidx-compose-material3-windowsizeclass = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "material3Compose" }
androidx-constraintlayout-compose = "androidx.constraintlayout:constraintlayout-compose:1.1.0-alpha04"
androidx-appcompat = "androidx.appcompat:appcompat:1.7.0-alpha01"
androidx-activity-compose = "androidx.activity:activity-compose:1.7.0-alpha02"
androidx-compose-constraintlayout = "androidx.constraintlayout:constraintlayout-compose:1.1.0-alpha04"
androidx-compose-activity = "androidx.activity:activity-compose:1.7.0-alpha02"
androidx-compose-paging = "androidx.paging:paging-compose:1.0.0-alpha17"

androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }

androidx-navigation-compose = "androidx.navigation:navigation-compose:2.6.0-alpha04"
androidx-paging-runtime = "androidx.paging:paging-runtime-ktx:3.2.0-alpha03"

androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.4.1"

accompanist-pager-core = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist-placeholder = { module = "com.google.accompanist:accompanist-placeholder", version.ref = "accompanist" }
accompanist-pager-indicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-appcompat-theme = { module = "com.google.accompanist:accompanist-appcompat-theme", version.ref = "accompanist" }
accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist" }
accompanist-navigation-animation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist" }
accompanist-insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanist" }
accompanist-insets-ui = { module = "com.google.accompanist:accompanist-insets-ui", version.ref = "accompanist" }

junit = "junit:junit:4.13.2"
androidx-test-ext-junit = "androidx.test.ext:junit:1.1.4"
androidx-test-espresso-core = "androidx.test.espresso:espresso-core:3.5.0"

landscapist-glide = "com.github.skydoves:landscapist-glide:1.6.1"

ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-android = { group = "io.ktor", name = "ktor-client-android", version.ref = "ktor" }
ktor-client-jvm = { group = "io.ktor", name = "ktor-client-logging-jvm", version.ref = "ktor" }
ktor-client-serialization-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-negotivation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
slf4j-android = { group = "org.slf4j", name = "slf4j-android", version = "1.7.7" }

koin-android = { group = "io.insert-koin", name = "koin-android", version = "3.3.0" }
koin-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version = "3.3.0" }
koin-ktor = { group = "io.insert-koin", name = "koin-ktor", version = "3.2.2" }
koin-logger-slf4j = { group = "io.insert-koin", name = "koin-logger-slf4j", version = "3.2.2" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
versions = { id = "com.github.ben-manes.versions", version = "0.44.0" }
vcu = { id = "nl.littlerobots.version-catalog-update", version = "0.7.0" }

[bundles]
accompanist = [
    "accompanist-pager-core",
    "accompanist-placeholder",
    "accompanist-pager-indicators",
    "accompanist-systemuicontroller",
    "accompanist-appcompat-theme",
    "accompanist-flowlayout",
    "accompanist-navigation-animation",
    "accompanist-insets",
    "accompanist-insets-ui",
]

compose = [
    "androidx-compose-ui-core",
    "androidx-compose-ui-tooling-preview",
    "androidx-compose-ui-tooling",
    "androidx-compose-material3",
    "androidx-compose-constraintlayout",
    "androidx-compose-activity",
    "androidx-compose-paging",
    "androidx-compose-material3-windowsizeclass"
]

lifecycle = [
    "androidx-lifecycle-runtime-ktx",
    "androidx-lifecycle-viewmodel-compose",
    "androidx-lifecycle-viewmodel-ktx"
]

coroutines = [
    "kotlinx-coroutines-core",
    "kotlinx-coroutines-android"
]

